"""RTL simulation verification tool for PLENA.

Verifies HBM and VRAM contents after RTL simulation by comparing
against golden expected results.

Usage:
    python -m verification.verify_rtl_sim --workload-dir /path/to/build

The workload directory should contain:
    - verification_params.json: Parameters for verification
    - golden_result.txt or golden_result.pt: Expected output
    - hbm_result.mem: HBM dump from simulation (generated by Verilator)
"""

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch


def parse_hbm_result_file(filepath: Path) -> Dict[int, int]:
    """Parse HBM result file - simple sequential format.

    File format:
        0xDATA_ROW_0
        0xDATA_ROW_1
        ...

    Args:
        filepath: Path to hbm_result.mem file

    Returns:
        Dictionary mapping row index to 256-bit data value
    """
    data = {}
    line_num = 0

    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("//"):
                continue

            # Parse hex data: 0x<hex>
            if line.startswith("0x") or line.startswith("0X"):
                data[line_num] = int(line, 16)
                line_num += 1

    return data


def read_hbm_elements_and_scales(
    hbm_data: Dict[int, int],
    start_addr: int,
    num_elements: int,
    row_width: int = 256,  # HBM row width (256 bits)
    mx_element_width: int = 8,  # Width per MX element (8 bits for 4+3+1)
    mx_scale_width: int = 8,    # Width per MX scale (8 bits)
    block_size: int = 8,        # Elements per block
    scale_offset: int = None,   # Byte offset from elements to scales
) -> Tuple[np.ndarray, np.ndarray]:
    """Extract elements and scales from unified HBM data.

    Args:
        hbm_data: Parsed HBM data {row_index: 256-bit value}
        start_addr: Starting byte address
        num_elements: Number of elements to read
        row_width: HBM row width in bits (256)
        mx_element_width: Width of each MX element in bits
        mx_scale_width: Width of each MX scale in bits
        block_size: Elements per scale block
        scale_offset: Byte offset from elements to scales

    Returns:
        Tuple of (elements array, scales array)
    """
    bytes_per_row = row_width // 8  # 32 bytes per row
    elements_per_row = row_width // mx_element_width

    # Extract elements
    elements = []
    for i in range(num_elements):
        byte_addr = start_addr + i * (mx_element_width // 8)
        row_idx = byte_addr // bytes_per_row
        byte_offset = byte_addr % bytes_per_row
        bit_offset = byte_offset * 8

        row_data = hbm_data.get(row_idx, 0)
        element = (row_data >> bit_offset) & ((1 << mx_element_width) - 1)
        elements.append(element)

    # Extract scales
    num_blocks = (num_elements + block_size - 1) // block_size
    scales = []
    scale_start_addr = (start_addr + scale_offset) if scale_offset else (start_addr + num_elements)

    for i in range(num_blocks):
        byte_addr = scale_start_addr + i * (mx_scale_width // 8)
        row_idx = byte_addr // bytes_per_row
        byte_offset = byte_addr % bytes_per_row
        bit_offset = byte_offset * 8

        row_data = hbm_data.get(row_idx, 0)
        scale = (row_data >> bit_offset) & ((1 << mx_scale_width) - 1)
        scales.append(scale)

    return np.array(elements, dtype=np.uint8), np.array(scales, dtype=np.uint8)


def mx_to_float(
    elements: np.ndarray,
    scales: np.ndarray,
    exp_width: int = 4,
    man_width: int = 3,
    scale_width: int = 8,
    block_size: int = 8,
) -> np.ndarray:
    """Convert MX format data to float.

    Args:
        elements: Raw element data (uint8 array)
        scales: Raw scale data (uint8 array)
        exp_width: Exponent width for elements
        man_width: Mantissa width for elements
        scale_width: Scale exponent width
        block_size: Elements per block

    Returns:
        Float array of converted values
    """
    values = []
    sign_mask = 1 << (exp_width + man_width)
    exp_mask = ((1 << exp_width) - 1) << man_width
    man_mask = (1 << man_width) - 1
    bias = (1 << (exp_width - 1)) - 1 if exp_width > 0 else 0
    scale_bias = 127  # E8M0 scale bias

    for i, elem in enumerate(elements):
        block_idx = i // block_size
        scale = scales[block_idx] if block_idx < len(scales) else 0

        # Parse element
        sign = (elem >> (exp_width + man_width)) & 1
        exp = (elem >> man_width) & ((1 << exp_width) - 1)
        man = elem & man_mask

        # Convert element to float
        if exp == 0:
            # Subnormal or zero
            if man == 0:
                elem_val = 0.0
            else:
                elem_val = ((-1) ** int(sign)) * (man / (2 ** man_width)) * (2 ** (1 - bias))
        elif exp == (1 << exp_width) - 1:
            # Inf/NaN
            elem_val = float('inf') if man == 0 else float('nan')
            if sign:
                elem_val = -elem_val
        else:
            # Normal
            elem_val = ((-1) ** int(sign)) * (1 + man / (2 ** man_width)) * (2 ** (exp - bias))

        # Apply scale (E8M0 format)
        scale_val = 2 ** (scale - scale_bias)
        values.append(elem_val * scale_val)

    return np.array(values, dtype=np.float32)


def compare_results(
    simulated: np.ndarray,
    golden: np.ndarray,
    atol: float = 0.1,
    rtol: float = 0.1,
) -> Dict:
    """Compare simulated results against golden reference.

    Args:
        simulated: Simulated output array
        golden: Golden reference array
        atol: Absolute tolerance
        rtol: Relative tolerance

    Returns:
        Dictionary with comparison metrics
    """
    # Ensure same length
    min_len = min(len(simulated), len(golden))
    simulated = simulated[:min_len]
    golden = golden[:min_len]

    # Convert to tensors for comparison
    sim_t = torch.from_numpy(simulated).float()
    gold_t = torch.from_numpy(golden).float()

    # Compute errors
    errors = torch.abs(sim_t - gold_t)

    # Metrics
    mse = torch.mean((sim_t - gold_t) ** 2).item()
    mae = torch.mean(errors).item()
    max_error = torch.max(errors).item()

    # Allclose check
    tolerance = atol + rtol * torch.abs(gold_t)
    within_tol = errors <= tolerance
    match_rate = torch.sum(within_tol).item() / len(errors) * 100

    # Pass criteria
    passed = match_rate >= 90.0

    return {
        "mse": mse,
        "mae": mae,
        "max_error": max_error,
        "match_rate": match_rate,
        "passed": passed,
        "num_compared": min_len,
        "atol": atol,
        "rtol": rtol,
    }


def parse_golden_file(filepath: Path) -> np.ndarray:
    """Parse golden result from .txt or .pt file.

    Args:
        filepath: Path to golden result file

    Returns:
        Flattened numpy array of golden values
    """
    if filepath.suffix == ".pt":
        tensor = torch.load(filepath)
        return tensor.float().numpy().flatten()

    # Parse text file
    with open(filepath, 'r') as f:
        content = f.read()

    # Find "Original Output:" section
    match = re.search(r"Original Output:\s*\[(.*?)\]", content, re.DOTALL)
    if not match:
        # Try tensor() format
        match = re.search(r"tensor\(\[(.*?)\]", content, re.DOTALL)

    if not match:
        raise ValueError("Could not find output values in golden file")

    values_text = match.group(1)
    values = []
    for line in values_text.strip().split("\n"):
        line = line.strip().strip(",").strip("[").strip("]")
        if not line:
            continue
        for val_str in line.replace(",", " ").split():
            try:
                val = float(val_str)
                values.append(val)
            except ValueError:
                continue

    return np.array(values, dtype=np.float32)


def verify_hbm(
    workload_dir: Path,
    params: Dict,
    verbose: bool = True,
) -> Dict:
    """Verify HBM contents against golden result.

    Args:
        workload_dir: Path to workload build directory
        params: Verification parameters
        verbose: Print detailed output

    Returns:
        Verification result dictionary
    """
    hbm_result_file = workload_dir / "hbm_result.mem"
    golden_file = workload_dir / "golden_result.pt"
    if not golden_file.exists():
        golden_file = workload_dir / "golden_result.txt"

    if not hbm_result_file.exists():
        return {"error": f"HBM result file not found: {hbm_result_file}"}

    if not golden_file.exists():
        return {"error": f"Golden file not found: {golden_file}"}

    # Parse HBM result
    hbm_data = parse_hbm_result_file(hbm_result_file)

    # Extract relevant parameters
    start_addr = params.get("result_hbm_start_byte", 0)
    num_elements = params.get("num_elements", 0)
    exp_width = params.get("exp_width", 4)
    man_width = params.get("man_width", 3)
    scale_width = params.get("scale_width", 8)
    block_size = params.get("block_size", 8)
    scale_offset = params.get("scale_offset")

    # Extract elements and scales
    elements, scales = read_hbm_elements_and_scales(
        hbm_data,
        start_addr=start_addr,
        num_elements=num_elements,
        block_size=block_size,
        scale_offset=scale_offset,
    )

    # Convert to float
    simulated = mx_to_float(
        elements, scales,
        exp_width=exp_width,
        man_width=man_width,
        scale_width=scale_width,
        block_size=block_size,
    )

    # Parse golden
    golden = parse_golden_file(golden_file)

    # Compare
    result = compare_results(simulated, golden)
    result["type"] = "hbm"

    if verbose:
        print("\n" + "=" * 60)
        print("HBM Verification Results")
        print("=" * 60)
        print(f"  Elements compared: {result['num_compared']}")
        print(f"  MSE: {result['mse']:.6e}")
        print(f"  MAE: {result['mae']:.6e}")
        print(f"  Max Error: {result['max_error']:.6f}")
        print(f"  Match Rate: {result['match_rate']:.2f}%")
        print(f"  Status: {'PASSED' if result['passed'] else 'FAILED'}")
        print("=" * 60)

    return result


def parse_vector_result_file(filepath: Path, row_width_bits: int = 192) -> List[int]:
    """Parse vector SRAM result file.

    File format (hex values, one per line):
        DATA_ROW_0
        DATA_ROW_1
        ...

    Args:
        filepath: Path to vector_result.mem file
        row_width_bits: Width of each row in bits (default: 192 for VLEN=16, FP12)

    Returns:
        List of row data values (as integers)
    """
    data = []

    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("//"):
                continue

            # Parse hex data (with or without 0x prefix)
            try:
                if line.startswith("0x") or line.startswith("0X"):
                    data.append(int(line, 16))
                else:
                    data.append(int(line, 16))
            except ValueError:
                continue

    return data


def fp_to_float(
    element: int,
    exp_width: int = 6,
    man_width: int = 5,
) -> float:
    """Convert FP format element to float.

    Args:
        element: Raw element data (uint, with sign+exp+mant)
        exp_width: Exponent width (default: 6 for V_FP_EXP_WIDTH)
        man_width: Mantissa width (default: 5 for V_FP_MANT_WIDTH)

    Returns:
        Float value
    """
    total_width = 1 + exp_width + man_width
    mask = (1 << total_width) - 1
    element = element & mask

    # Extract fields
    sign = (element >> (exp_width + man_width)) & 1
    exp = (element >> man_width) & ((1 << exp_width) - 1)
    man = element & ((1 << man_width) - 1)

    bias = (1 << (exp_width - 1)) - 1  # bias = 31 for exp_width=6

    if exp == 0:
        # Subnormal or zero
        if man == 0:
            return 0.0
        # Subnormal: implicit leading 0
        val = (man / (2 ** man_width)) * (2 ** (1 - bias))
    elif exp == (1 << exp_width) - 1:
        # Inf/NaN
        if man == 0:
            return float('-inf') if sign else float('inf')
        return float('nan')
    else:
        # Normal: implicit leading 1
        val = (1 + man / (2 ** man_width)) * (2 ** (exp - bias))

    return -val if sign else val


def extract_fp_elements_from_row(
    row_data: int,
    num_elements: int = 16,
    exp_width: int = 6,
    man_width: int = 5,
) -> List[float]:
    """Extract FP elements from a row and convert to floats.

    Args:
        row_data: Row data as integer
        num_elements: Number of elements per row (VLEN)
        exp_width: FP exponent width
        man_width: FP mantissa width

    Returns:
        List of float values
    """
    element_width = 1 + exp_width + man_width
    element_mask = (1 << element_width) - 1

    values = []
    for i in range(num_elements):
        elem = (row_data >> (i * element_width)) & element_mask
        values.append(fp_to_float(elem, exp_width, man_width))

    return values


def save_vector_result_as_fp(
    filepath: Path,
    output_path: Path,
    vlen: int = 16,
    exp_width: int = 6,
    man_width: int = 5,
    start_row: int = 0,
    num_rows: Optional[int] = None,
    format: str = "txt",
) -> Path:
    """Save vector_result.mem as floating point values to a file.

    Args:
        filepath: Path to vector_result.mem file
        output_path: Path to output file (without extension)
        vlen: Number of elements per row (VLEN)
        exp_width: FP exponent width (V_FP_EXP_WIDTH)
        man_width: FP mantissa width (V_FP_MANT_WIDTH)
        start_row: Starting row index
        num_rows: Number of rows to process (None = all)
        format: Output format - "txt" (human readable) or "mem" (one value per line)

    Returns:
        Path to the created output file
    """
    vram_data = parse_vector_result_file(filepath)
    if not vram_data:
        raise ValueError(f"No data found in {filepath}")

    total_rows = len(vram_data)
    end_row = total_rows if num_rows is None else min(start_row + num_rows, total_rows)

    element_width = 1 + exp_width + man_width
    fp_format = f"FP{element_width} (1s + {exp_width}e + {man_width}m)"

    # Extract all FP values
    all_fp_values = []
    row_fp_values = []
    for row_idx in range(start_row, end_row):
        row_floats = extract_fp_elements_from_row(
            vram_data[row_idx],
            num_elements=vlen,
            exp_width=exp_width,
            man_width=man_width,
        )
        row_fp_values.append((row_idx, row_floats))
        all_fp_values.extend(row_floats)

    # Determine output file path
    if format == "mem":
        out_file = output_path.with_suffix(".fp.mem")
    else:
        out_file = output_path.with_suffix(".fp.txt")

    with open(out_file, 'w') as f:
        if format == "txt":
            # Human-readable format with header
            f.write(f"# Vector Result FP Values\n")
            f.write(f"# Source: {filepath}\n")
            f.write(f"# VLEN: {vlen}, Format: {fp_format}\n")
            f.write(f"# Rows: {start_row} to {end_row - 1} ({end_row - start_row} rows)\n")
            f.write(f"# Total elements: {len(all_fp_values)}\n")
            f.write("#\n")
            for row_idx, row_floats in row_fp_values:
                f.write(f"Row {row_idx:4d}: ")
                f.write(" ".join(f"{v:12.6f}" for v in row_floats))
                f.write("\n")
        else:
            # .mem format - one value per line for easy parsing
            f.write(f"// Vector Result FP Values (VLEN={vlen}, {fp_format})\n")
            f.write(f"// Source: {filepath}\n")
            f.write(f"// Rows: {start_row} to {end_row - 1}\n")
            for row_idx, row_floats in row_fp_values:
                f.write(f"// Row {row_idx}\n")
                for v in row_floats:
                    f.write(f"{v:.8e}\n")

    return out_file


def verify_vram(
    workload_dir: Path,
    params: Dict,
    verbose: bool = True,
    save_fp_result: bool = True,
) -> Dict:
    """Verify VRAM (vector SRAM) contents against golden result.

    Uses configurable FP format from params or defaults to FP12
    (V_FP_EXP_WIDTH=6, V_FP_MANT_WIDTH=5).

    Args:
        workload_dir: Path to workload build directory
        params: Verification parameters (can include v_fp_exp_width, v_fp_man_width)
        verbose: Print detailed output
        save_fp_result: Save FP-converted values to file (default: True)

    Returns:
        Verification result dictionary
    """
    vram_result_file = workload_dir / "vector_result.mem"
    golden_file = workload_dir / "golden_result.pt"
    if not golden_file.exists():
        golden_file = workload_dir / "golden_result.txt"

    if not vram_result_file.exists():
        return {"error": f"VRAM result file not found: {vram_result_file}"}

    if vram_result_file.stat().st_size == 0:
        return {"error": "VRAM result file is empty (0 bytes)"}

    if not golden_file.exists():
        return {"error": f"Golden file not found: {golden_file}"}

    # Parse VRAM result
    vram_data = parse_vector_result_file(vram_result_file)

    if not vram_data:
        return {"error": "No data found in VRAM result file"}

    # FP precision - configurable via params, defaults from precision.svh
    exp_width = params.get("v_fp_exp_width", 6)
    man_width = params.get("v_fp_man_width", 5)
    vlen = params.get("row_dim", params.get("vlen", 16))

    # Extract parameters
    start_row = params.get("vram_start_row_idx", params.get("start_row_idx", 0))
    num_rows = params.get("vram_num_rows", params.get("num_rows", len(vram_data)))

    if verbose:
        print(f"\nVRAM file has {len(vram_data)} rows")
        print(f"Checking rows {start_row} to {start_row + num_rows - 1}")
        print(f"FP format: exp_width={exp_width}, man_width={man_width}, VLEN={vlen}")

    # Extract all float values (row by row for saving)
    simulated_values = []
    row_fp_values = []
    for row_idx in range(start_row, min(start_row + num_rows, len(vram_data))):
        row_floats = extract_fp_elements_from_row(
            vram_data[row_idx],
            num_elements=vlen,
            exp_width=exp_width,
            man_width=man_width,
        )
        row_fp_values.append((row_idx, row_floats))
        simulated_values.extend(row_floats)

    if not simulated_values:
        return {"error": "No valid data extracted from VRAM"}

    simulated = np.array(simulated_values, dtype=np.float32)

    # Save FP results to file if requested
    fp_output_file = None
    if save_fp_result:
        fp_output_file = workload_dir / "vector_result.fp.txt"
        element_width = 1 + exp_width + man_width
        fp_format = f"FP{element_width} (1s + {exp_width}e + {man_width}m)"

        with open(fp_output_file, 'w') as f:
            f.write(f"# Vector Result FP Values\n")
            f.write(f"# Source: {vram_result_file}\n")
            f.write(f"# VLEN: {vlen}, Format: {fp_format}\n")
            f.write(f"# Rows: {start_row} to {start_row + num_rows - 1}\n")
            f.write(f"# Total elements: {len(simulated_values)}\n")
            f.write("#\n")
            for row_idx, row_floats in row_fp_values:
                f.write(f"Row {row_idx:4d}: ")
                f.write(" ".join(f"{v:12.6f}" for v in row_floats))
                f.write("\n")

        if verbose:
            print(f"FP results saved to: {fp_output_file}")

    # Parse golden
    golden = parse_golden_file(golden_file)

    # Compare
    result = compare_results(simulated, golden)
    result["type"] = "vram"
    result["rows_checked"] = min(num_rows, len(vram_data) - start_row)
    result["fp_exp_width"] = exp_width
    result["fp_man_width"] = man_width
    result["vlen"] = vlen
    if fp_output_file:
        result["fp_output_file"] = str(fp_output_file)

    if verbose:
        print("\n" + "=" * 60)
        print("VRAM Verification Results")
        print("=" * 60)
        print(f"  FP Format: {1 + exp_width + man_width}-bit (1s + {exp_width}e + {man_width}m)")
        print(f"  VLEN: {vlen}")
        print(f"  Rows checked: {result['rows_checked']}")
        print(f"  Elements compared: {result['num_compared']}")
        print(f"  MSE: {result['mse']:.6e}")
        print(f"  MAE: {result['mae']:.6e}")
        print(f"  Max Error: {result['max_error']:.6f}")
        print(f"  Match Rate: {result['match_rate']:.2f}%")
        print(f"  Status: {'PASSED' if result['passed'] else 'FAILED'}")
        print("=" * 60)

        # Show sample values if verbose
        if len(simulated_values) > 0:
            print(f"\nFirst 8 simulated values: {simulated_values[:8]}")
            print(f"First 8 golden values:    {list(golden[:8])}")

    return result


def main():
    """Main entry point for RTL simulation verification."""
    parser = argparse.ArgumentParser(
        description="Verify RTL simulation results against golden reference"
    )
    parser.add_argument(
        "--workload-dir",
        type=str,
        required=True,
        help="Path to workload build directory"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Print detailed output"
    )
    parser.add_argument(
        "--check-hbm",
        action="store_true",
        default=True,
        help="Check HBM contents (default: True)"
    )
    parser.add_argument(
        "--check-vram",
        action="store_true",
        default=False,
        help="Check VRAM contents"
    )
    parser.add_argument(
        "--save-fp",
        action="store_true",
        default=True,
        help="Save FP-converted VRAM results to .fp.txt file (default: True)"
    )
    parser.add_argument(
        "--no-save-fp",
        action="store_true",
        help="Disable saving FP-converted results"
    )
    parser.add_argument(
        "--vlen",
        type=int,
        default=None,
        help="Override VLEN (elements per row)"
    )
    parser.add_argument(
        "--exp-width",
        type=int,
        default=None,
        help="Override V_FP_EXP_WIDTH (default: from params or 6)"
    )
    parser.add_argument(
        "--man-width",
        type=int,
        default=None,
        help="Override V_FP_MANT_WIDTH (default: from params or 5)"
    )
    args = parser.parse_args()

    workload_dir = Path(args.workload_dir)

    # Load verification parameters
    params_file = workload_dir / "verification_params.json"
    if not params_file.exists():
        params_file = workload_dir / "comparison_params.json"

    if not params_file.exists():
        print(f"Error: No verification parameters file found in {workload_dir}")
        sys.exit(1)

    with open(params_file) as f:
        params = json.load(f)

    # Override params with command line arguments
    if args.vlen is not None:
        params["vlen"] = args.vlen
        params["row_dim"] = args.vlen
    if args.exp_width is not None:
        params["v_fp_exp_width"] = args.exp_width
    if args.man_width is not None:
        params["v_fp_man_width"] = args.man_width

    if args.verbose:
        print(f"Verification parameters loaded from: {params_file}")
        print(f"Workload type: {params.get('workload_type', 'unknown')}")
        if args.exp_width or args.man_width or args.vlen:
            print(f"Overrides: vlen={params.get('vlen')}, "
                  f"exp_width={params.get('v_fp_exp_width')}, "
                  f"man_width={params.get('v_fp_man_width')}")

    results = {}
    all_passed = True

    # HBM verification
    if args.check_hbm or params.get("check_hbm", False):
        hbm_result = verify_hbm(workload_dir, params, verbose=args.verbose)
        results["hbm"] = hbm_result
        if hbm_result.get("error") or not hbm_result.get("passed", False):
            all_passed = False

    # VRAM verification
    save_fp = args.save_fp and not args.no_save_fp
    if args.check_vram or params.get("check_vram", False):
        vram_result = verify_vram(
            workload_dir, params,
            verbose=args.verbose,
            save_fp_result=save_fp
        )
        results["vram"] = vram_result
        if vram_result.get("error") or not vram_result.get("passed", False):
            all_passed = False

    # Summary
    print("\n" + "=" * 60)
    print("Verification Summary")
    print("=" * 60)
    for check_type, result in results.items():
        if "error" in result:
            print(f"  {check_type.upper()}: ERROR - {result['error']}")
        else:
            status = "PASSED" if result.get("passed", False) else "FAILED"
            print(f"  {check_type.upper()}: {status} (match rate: {result.get('match_rate', 0):.2f}%)")
            if "fp_output_file" in result:
                print(f"    FP results: {result['fp_output_file']}")
    print("=" * 60)
    print(f"Overall: {'PASSED' if all_passed else 'FAILED'}")
    print("=" * 60)

    sys.exit(0 if all_passed else 1)


if __name__ == "__main__":
    main()
