"""RTL simulation verification tool for PLENA.

Verifies HBM and VRAM contents after RTL simulation by comparing
against golden expected results.

Usage:
    python -m verification.verify_rtl_sim --workload-dir /path/to/build

The workload directory should contain:
    - verification_params.json: Parameters for verification
    - golden_result.txt or golden_result.pt: Expected output
    - hbm_result.mem: HBM dump from simulation (generated by Verilator)
"""

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch


def parse_hbm_result_file(filepath: Path) -> Dict[int, int]:
    """Parse HBM result file - simple sequential format.

    File format:
        0xDATA_ROW_0
        0xDATA_ROW_1
        ...

    Args:
        filepath: Path to hbm_result.mem file

    Returns:
        Dictionary mapping row index to 256-bit data value
    """
    data = {}
    line_num = 0

    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("//"):
                continue

            # Parse hex data: 0x<hex>
            if line.startswith("0x") or line.startswith("0X"):
                data[line_num] = int(line, 16)
                line_num += 1

    return data


def read_hbm_elements_and_scales(
    hbm_data: Dict[int, int],
    start_addr: int,
    num_elements: int,
    row_width: int = 256,  # HBM row width (256 bits)
    mx_element_width: int = 8,  # Width per MX element (8 bits for 4+3+1)
    mx_scale_width: int = 8,    # Width per MX scale (8 bits)
    block_size: int = 8,        # Elements per block
    scale_offset: int = None,   # Byte offset from elements to scales
) -> Tuple[np.ndarray, np.ndarray]:
    """Extract elements and scales from unified HBM data.

    Args:
        hbm_data: Parsed HBM data {row_index: 256-bit value}
        start_addr: Starting byte address
        num_elements: Number of elements to read
        row_width: HBM row width in bits (256)
        mx_element_width: Width of each MX element in bits
        mx_scale_width: Width of each MX scale in bits
        block_size: Elements per scale block
        scale_offset: Byte offset from elements to scales

    Returns:
        Tuple of (elements array, scales array)
    """
    bytes_per_row = row_width // 8  # 32 bytes per row
    elements_per_row = row_width // mx_element_width

    # Extract elements
    elements = []
    for i in range(num_elements):
        byte_addr = start_addr + i * (mx_element_width // 8)
        row_idx = byte_addr // bytes_per_row
        byte_offset = byte_addr % bytes_per_row
        bit_offset = byte_offset * 8

        row_data = hbm_data.get(row_idx, 0)
        element = (row_data >> bit_offset) & ((1 << mx_element_width) - 1)
        elements.append(element)

    # Extract scales
    num_blocks = (num_elements + block_size - 1) // block_size
    scales = []
    scale_start_addr = (start_addr + scale_offset) if scale_offset else (start_addr + num_elements)

    for i in range(num_blocks):
        byte_addr = scale_start_addr + i * (mx_scale_width // 8)
        row_idx = byte_addr // bytes_per_row
        byte_offset = byte_addr % bytes_per_row
        bit_offset = byte_offset * 8

        row_data = hbm_data.get(row_idx, 0)
        scale = (row_data >> bit_offset) & ((1 << mx_scale_width) - 1)
        scales.append(scale)

    return np.array(elements, dtype=np.uint8), np.array(scales, dtype=np.uint8)


def mx_to_float(
    elements: np.ndarray,
    scales: np.ndarray,
    exp_width: int = 4,
    man_width: int = 3,
    scale_width: int = 8,
    block_size: int = 8,
) -> np.ndarray:
    """Convert MX format data to float.

    Args:
        elements: Raw element data (uint8 array)
        scales: Raw scale data (uint8 array)
        exp_width: Exponent width for elements
        man_width: Mantissa width for elements
        scale_width: Scale exponent width
        block_size: Elements per block

    Returns:
        Float array of converted values
    """
    values = []
    sign_mask = 1 << (exp_width + man_width)
    exp_mask = ((1 << exp_width) - 1) << man_width
    man_mask = (1 << man_width) - 1
    bias = (1 << (exp_width - 1)) - 1 if exp_width > 0 else 0
    scale_bias = 127  # E8M0 scale bias

    for i, elem in enumerate(elements):
        block_idx = i // block_size
        scale = scales[block_idx] if block_idx < len(scales) else 0

        # Parse element
        sign = (elem >> (exp_width + man_width)) & 1
        exp = (elem >> man_width) & ((1 << exp_width) - 1)
        man = elem & man_mask

        # Convert element to float
        if exp == 0:
            # Subnormal or zero
            if man == 0:
                elem_val = 0.0
            else:
                elem_val = ((-1) ** int(sign)) * (man / (2 ** man_width)) * (2 ** (1 - bias))
        elif exp == (1 << exp_width) - 1:
            # Inf/NaN
            elem_val = float('inf') if man == 0 else float('nan')
            if sign:
                elem_val = -elem_val
        else:
            # Normal
            elem_val = ((-1) ** int(sign)) * (1 + man / (2 ** man_width)) * (2 ** (exp - bias))

        # Apply scale (E8M0 format)
        scale_val = 2 ** (scale - scale_bias)
        values.append(elem_val * scale_val)

    return np.array(values, dtype=np.float32)


def compare_results(
    simulated: np.ndarray,
    golden: np.ndarray,
    atol: float = 0.1,
    rtol: float = 0.1,
) -> Dict:
    """Compare simulated results against golden reference.

    Args:
        simulated: Simulated output array
        golden: Golden reference array
        atol: Absolute tolerance
        rtol: Relative tolerance

    Returns:
        Dictionary with comparison metrics
    """
    # Ensure same length
    min_len = min(len(simulated), len(golden))
    simulated = simulated[:min_len]
    golden = golden[:min_len]

    # Convert to tensors for comparison
    sim_t = torch.from_numpy(simulated).float()
    gold_t = torch.from_numpy(golden).float()

    # Compute errors
    errors = torch.abs(sim_t - gold_t)

    # Metrics
    mse = torch.mean((sim_t - gold_t) ** 2).item()
    mae = torch.mean(errors).item()
    max_error = torch.max(errors).item()

    # Allclose check
    tolerance = atol + rtol * torch.abs(gold_t)
    within_tol = errors <= tolerance
    match_rate = torch.sum(within_tol).item() / len(errors) * 100

    # Pass criteria
    passed = match_rate >= 90.0

    return {
        "mse": mse,
        "mae": mae,
        "max_error": max_error,
        "match_rate": match_rate,
        "passed": passed,
        "num_compared": min_len,
        "atol": atol,
        "rtol": rtol,
    }


def parse_golden_file(filepath: Path) -> np.ndarray:
    """Parse golden result from .txt or .pt file.

    Args:
        filepath: Path to golden result file

    Returns:
        Flattened numpy array of golden values
    """
    if filepath.suffix == ".pt":
        tensor = torch.load(filepath)
        return tensor.float().numpy().flatten()

    # Parse text file
    with open(filepath, 'r') as f:
        content = f.read()

    # Find "Original Output:" section
    match = re.search(r"Original Output:\s*\[(.*?)\]", content, re.DOTALL)
    if not match:
        # Try tensor() format
        match = re.search(r"tensor\(\[(.*?)\]", content, re.DOTALL)

    if not match:
        raise ValueError("Could not find output values in golden file")

    values_text = match.group(1)
    values = []
    for line in values_text.strip().split("\n"):
        line = line.strip().strip(",").strip("[").strip("]")
        if not line:
            continue
        for val_str in line.replace(",", " ").split():
            try:
                val = float(val_str)
                values.append(val)
            except ValueError:
                continue

    return np.array(values, dtype=np.float32)


def verify_hbm(
    workload_dir: Path,
    params: Dict,
    verbose: bool = True,
) -> Dict:
    """Verify HBM contents against golden result.

    Args:
        workload_dir: Path to workload build directory
        params: Verification parameters
        verbose: Print detailed output

    Returns:
        Verification result dictionary
    """
    hbm_result_file = workload_dir / "hbm_result.mem"
    golden_file = workload_dir / "golden_result.pt"
    if not golden_file.exists():
        golden_file = workload_dir / "golden_result.txt"

    if not hbm_result_file.exists():
        return {"error": f"HBM result file not found: {hbm_result_file}"}

    if not golden_file.exists():
        return {"error": f"Golden file not found: {golden_file}"}

    # Parse HBM result
    hbm_data = parse_hbm_result_file(hbm_result_file)

    # Extract relevant parameters
    start_addr = params.get("result_hbm_start_byte", 0)
    num_elements = params.get("num_elements", 0)
    exp_width = params.get("exp_width", 4)
    man_width = params.get("man_width", 3)
    scale_width = params.get("scale_width", 8)
    block_size = params.get("block_size", 8)
    scale_offset = params.get("scale_offset")

    # Extract elements and scales
    elements, scales = read_hbm_elements_and_scales(
        hbm_data,
        start_addr=start_addr,
        num_elements=num_elements,
        block_size=block_size,
        scale_offset=scale_offset,
    )

    # Convert to float
    simulated = mx_to_float(
        elements, scales,
        exp_width=exp_width,
        man_width=man_width,
        scale_width=scale_width,
        block_size=block_size,
    )

    # Parse golden
    golden = parse_golden_file(golden_file)

    # Compare
    result = compare_results(simulated, golden)
    result["type"] = "hbm"

    if verbose:
        print("\n" + "=" * 60)
        print("HBM Verification Results")
        print("=" * 60)
        print(f"  Elements compared: {result['num_compared']}")
        print(f"  MSE: {result['mse']:.6e}")
        print(f"  MAE: {result['mae']:.6e}")
        print(f"  Max Error: {result['max_error']:.6f}")
        print(f"  Match Rate: {result['match_rate']:.2f}%")
        print(f"  Status: {'PASSED' if result['passed'] else 'FAILED'}")
        print("=" * 60)

    return result


def main():
    """Main entry point for RTL simulation verification."""
    parser = argparse.ArgumentParser(
        description="Verify RTL simulation results against golden reference"
    )
    parser.add_argument(
        "--workload-dir",
        type=str,
        required=True,
        help="Path to workload build directory"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Print detailed output"
    )
    parser.add_argument(
        "--check-hbm",
        action="store_true",
        default=True,
        help="Check HBM contents (default: True)"
    )
    parser.add_argument(
        "--check-vram",
        action="store_true",
        default=False,
        help="Check VRAM contents"
    )
    args = parser.parse_args()

    workload_dir = Path(args.workload_dir)

    # Load verification parameters
    params_file = workload_dir / "verification_params.json"
    if not params_file.exists():
        params_file = workload_dir / "comparison_params.json"

    if not params_file.exists():
        print(f"Error: No verification parameters file found in {workload_dir}")
        sys.exit(1)

    with open(params_file) as f:
        params = json.load(f)

    if args.verbose:
        print(f"Verification parameters loaded from: {params_file}")
        print(f"Workload type: {params.get('workload_type', 'unknown')}")

    results = {}
    all_passed = True

    # HBM verification
    if args.check_hbm or params.get("check_hbm", False):
        hbm_result = verify_hbm(workload_dir, params, verbose=args.verbose)
        results["hbm"] = hbm_result
        if hbm_result.get("error") or not hbm_result.get("passed", False):
            all_passed = False

    # Summary
    print("\n" + "=" * 60)
    print("Verification Summary")
    print("=" * 60)
    for check_type, result in results.items():
        if "error" in result:
            print(f"  {check_type.upper()}: ERROR - {result['error']}")
        else:
            status = "PASSED" if result.get("passed", False) else "FAILED"
            print(f"  {check_type.upper()}: {status} (match rate: {result.get('match_rate', 0):.2f}%)")
    print("=" * 60)
    print(f"Overall: {'PASSED' if all_passed else 'FAILED'}")
    print("=" * 60)

    sys.exit(0 if all_passed else 1)


if __name__ == "__main__":
    main()
